### ISSUE TITLE
Cannot create upsource.json

### ISSUE THREAD

**Issue by PieterSwitten** [kasperbauer/vscode-upsource#1]
When I do 'Upsource: setup' and fill in all my credentials there is no upsource.json created so I get this notification when I try to do anything.

![image](https://user-images.githubusercontent.com/10957732/31167235-aa60a224-a8f1-11e7-9ed4-7e1df9d50612.png)

I have reinstalled the plugin and did multiple times the 'Upsource: setup'.

**Comment by PieterSwitten** [comment]
I have my project opened and my project is only one folder. Normally there are no problems with write permissions.

Here is a screenshot of my developer tools:
![image](https://user-images.githubusercontent.com/10957732/31176045-b906f164-a911-11e7-8f31-7aced74c1f2c.png)

**Comment by kasperbauer** [comment]
Thx, I'll look into it.

**Comment by jeroencornelissen** [comment]
+1

**Comment by kasperbauer** [comment]
Fixed. The extension should update soon. :)
